name: benji_aggregator
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl_phone_field: ^3.2.0
  intl: ^0.18.1
  flutter_pw_validator: ^1.6.0
  csc_picker: ^0.2.7
  image_picker: ^1.0.1
  flutter_spinkit: ^5.2.0
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.4.0
  hexcolor: ^3.0.1
  get: ^4.6.5
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  url_launcher: ^6.1.12
  shimmer: ^3.0.0-nullsafety.0
  liquid_pull_to_refresh: ^3.0.1
  readmore: ^2.2.0
  dotted_border: ^2.0.0+3
  video_player: ^2.7.0
  font_awesome_flutter: ^10.5.0
  shared_preferences:
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  image: assets/images/splash_screen/frame_1.png
  color: "#f9f9f9"
  image_dark: assets/images/splash_screen/frame_1.png
  color_dark: "#000000"

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/images/logo/benji_red_logo_icon.jpg"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo/
    - assets/images/vendors/
    - assets/images/splash_screen/
    - assets/images/onboarding_screen/
    - assets/images/login/
    - assets/images/home/
    - assets/images/vendors/
    - assets/images/customer/
    - assets/images/products/
    - assets/icons/
    - assets/images/rider/
    - assets/images/profile/
    - assets/animations/splash_screen/
    - assets/animations/successful/
    - assets/videos/splash_screen/

  #For example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
